default: &default
  adapter: postgresql
  encoding: unicode
  user: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: onebitgames_api_development

test:
  <<: *default
  database: onebitgames_api_test

production:
  <<: *default
  database: onebitgames_api_production
  username: onebitgames_api
  password: <%= ENV['ONEBITGAMES_API_DATABASE_PASSWORD'] %>
